name: Build and Deploy
on:
  push:
    branches:
      - borrow-dynamics

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      GCP_WORKLOAD_ID: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      APP_DIRECTORY: sui-scallop-indexer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Deploy to VM
        run: |
          echo "${{ env.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh -o "StrictHostKeyChecking=no" -i id_rsa ${{ env.SSH_USERNAME }}@${{ env.SSH_HOST }} "cd ${{ env.APP_DIRECTORY }} && git pull && pnpm install && pnpm run build && pm2 restart all"
