name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: './Dockerfile'
          context: .
          push: true
          tags: nathan7scallop/scallop-sui-indexer:latest
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop scallop-sui-indexer-testnet
            docker stop scallop-sui-indexer-mainnet
            docker rm scallop-sui-indexer-testnet
            docker rm scallop-sui-indexer-mainnet
            docker rmi nathan7scallop/scallop-sui-indexer:latest
            docker pull nathan7scallop/scallop-sui-indexer:latest
            docker run -d --restart unless-stopped --log-opt max-size=500m --log-opt max-file=3 --name scallop-sui-indexer-testnet --env-file /usr/local/src/envs/.prod-testnet.env nathan7scallop/scallop-sui-indexer:latest
            docker run -d --restart unless-stopped --log-opt max-size=500m --log-opt max-file=3 --name scallop-sui-indexer-mainnet --env-file /usr/local/src/envs/.prod-mainnet.env nathan7scallop/scallop-sui-indexer:latest